# Generated by Django 5.2.5 on 2025-08-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_vuelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional')], max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
